// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/protocol/cluster.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterStatus int32

const (
	RegisterStatus_UNKNOWN RegisterStatus = 0
	RegisterStatus_SUCCESS RegisterStatus = 1
	RegisterStatus_FAILED  RegisterStatus = 2
)

// Enum value maps for RegisterStatus.
var (
	RegisterStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "SUCCESS",
		2: "FAILED",
	}
	RegisterStatus_value = map[string]int32{
		"UNKNOWN": 0,
		"SUCCESS": 1,
		"FAILED":  2,
	}
)

func (x RegisterStatus) Enum() *RegisterStatus {
	p := new(RegisterStatus)
	*p = x
	return p
}

func (x RegisterStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RegisterStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_protocol_cluster_proto_enumTypes[0].Descriptor()
}

func (RegisterStatus) Type() protoreflect.EnumType {
	return &file_internal_protocol_cluster_proto_enumTypes[0]
}

func (x RegisterStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RegisterStatus.Descriptor instead.
func (RegisterStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_protocol_cluster_proto_rawDescGZIP(), []int{0}
}

type RegisterNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Port          int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeRequest) Reset() {
	*x = RegisterNodeRequest{}
	mi := &file_internal_protocol_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeRequest) ProtoMessage() {}

func (x *RegisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_internal_protocol_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterNodeRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *RegisterNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterNodeRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RegisterNodeRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type RegisterNodeResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Status           RegisterStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=cluster.RegisterStatus" json:"status,omitempty"`
	Message          string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AssignedProtocol *ProtocolAssignment    `protobuf:"bytes,3,opt,name=assigned_protocol,json=assignedProtocol,proto3" json:"assigned_protocol,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterNodeResponse) Reset() {
	*x = RegisterNodeResponse{}
	mi := &file_internal_protocol_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeResponse) ProtoMessage() {}

func (x *RegisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_internal_protocol_cluster_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterNodeResponse) GetStatus() RegisterStatus {
	if x != nil {
		return x.Status
	}
	return RegisterStatus_UNKNOWN
}

func (x *RegisterNodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterNodeResponse) GetAssignedProtocol() *ProtocolAssignment {
	if x != nil {
		return x.AssignedProtocol
	}
	return nil
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ClusterId     string                 `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_internal_protocol_cluster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_cluster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_internal_protocol_cluster_proto_rawDescGZIP(), []int{2}
}

func (x *HeartbeatRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HeartbeatRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_internal_protocol_cluster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_cluster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_internal_protocol_cluster_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type PeersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeersRequest) Reset() {
	*x = PeersRequest{}
	mi := &file_internal_protocol_cluster_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeersRequest) ProtoMessage() {}

func (x *PeersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_cluster_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeersRequest.ProtoReflect.Descriptor instead.
func (*PeersRequest) Descriptor() ([]byte, []int) {
	return file_internal_protocol_cluster_proto_rawDescGZIP(), []int{4}
}

func (x *PeersRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

type PeersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Peers         []*NodeInfo            `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeersResponse) Reset() {
	*x = PeersResponse{}
	mi := &file_internal_protocol_cluster_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeersResponse) ProtoMessage() {}

func (x *PeersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_cluster_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeersResponse.ProtoReflect.Descriptor instead.
func (*PeersResponse) Descriptor() ([]byte, []int) {
	return file_internal_protocol_cluster_proto_rawDescGZIP(), []int{5}
}

func (x *PeersResponse) GetPeers() []*NodeInfo {
	if x != nil {
		return x.Peers
	}
	return nil
}

type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Port          uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_internal_protocol_cluster_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_cluster_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_internal_protocol_cluster_proto_rawDescGZIP(), []int{6}
}

func (x *NodeInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *NodeInfo) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type LogRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Level         string                 `protobuf:"bytes,4,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_internal_protocol_cluster_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_cluster_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_internal_protocol_cluster_proto_rawDescGZIP(), []int{7}
}

func (x *LogRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *LogRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *LogRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *LogRequest) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogResponse) Reset() {
	*x = LogResponse{}
	mi := &file_internal_protocol_cluster_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogResponse) ProtoMessage() {}

func (x *LogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_cluster_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogResponse.ProtoReflect.Descriptor instead.
func (*LogResponse) Descriptor() ([]byte, []int) {
	return file_internal_protocol_cluster_proto_rawDescGZIP(), []int{8}
}

func (x *LogResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type NodeActionCapabilities struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KvPut         bool                   `protobuf:"varint,1,opt,name=kv_put,json=kvPut,proto3" json:"kv_put,omitempty"`
	KvGet         bool                   `protobuf:"varint,2,opt,name=kv_get,json=kvGet,proto3" json:"kv_get,omitempty"`
	KvDelete      bool                   `protobuf:"varint,3,opt,name=kv_delete,json=kvDelete,proto3" json:"kv_delete,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeActionCapabilities) Reset() {
	*x = NodeActionCapabilities{}
	mi := &file_internal_protocol_cluster_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeActionCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeActionCapabilities) ProtoMessage() {}

func (x *NodeActionCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_cluster_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeActionCapabilities.ProtoReflect.Descriptor instead.
func (*NodeActionCapabilities) Descriptor() ([]byte, []int) {
	return file_internal_protocol_cluster_proto_rawDescGZIP(), []int{9}
}

func (x *NodeActionCapabilities) GetKvPut() bool {
	if x != nil {
		return x.KvPut
	}
	return false
}

func (x *NodeActionCapabilities) GetKvGet() bool {
	if x != nil {
		return x.KvGet
	}
	return false
}

func (x *NodeActionCapabilities) GetKvDelete() bool {
	if x != nil {
		return x.KvDelete
	}
	return false
}

type ReportNodeCapabilitiesRequest struct {
	state          protoimpl.MessageState  `protogen:"open.v1"`
	ClusterId      string                  `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	NodeId         string                  `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	ActiveProtocol *ProtocolAssignment     `protobuf:"bytes,3,opt,name=active_protocol,json=activeProtocol,proto3" json:"active_protocol,omitempty"`
	Actions        *NodeActionCapabilities `protobuf:"bytes,4,opt,name=actions,proto3" json:"actions,omitempty"`
	ReportedAt     int64                   `protobuf:"varint,5,opt,name=reported_at,json=reportedAt,proto3" json:"reported_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReportNodeCapabilitiesRequest) Reset() {
	*x = ReportNodeCapabilitiesRequest{}
	mi := &file_internal_protocol_cluster_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportNodeCapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportNodeCapabilitiesRequest) ProtoMessage() {}

func (x *ReportNodeCapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_cluster_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportNodeCapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*ReportNodeCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_internal_protocol_cluster_proto_rawDescGZIP(), []int{10}
}

func (x *ReportNodeCapabilitiesRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *ReportNodeCapabilitiesRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ReportNodeCapabilitiesRequest) GetActiveProtocol() *ProtocolAssignment {
	if x != nil {
		return x.ActiveProtocol
	}
	return nil
}

func (x *ReportNodeCapabilitiesRequest) GetActions() *NodeActionCapabilities {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *ReportNodeCapabilitiesRequest) GetReportedAt() int64 {
	if x != nil {
		return x.ReportedAt
	}
	return 0
}

type ReportNodeCapabilitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportNodeCapabilitiesResponse) Reset() {
	*x = ReportNodeCapabilitiesResponse{}
	mi := &file_internal_protocol_cluster_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportNodeCapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportNodeCapabilitiesResponse) ProtoMessage() {}

func (x *ReportNodeCapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_cluster_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportNodeCapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*ReportNodeCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_internal_protocol_cluster_proto_rawDescGZIP(), []int{11}
}

func (x *ReportNodeCapabilitiesResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *ReportNodeCapabilitiesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_protocol_cluster_proto protoreflect.FileDescriptor

const file_internal_protocol_cluster_proto_rawDesc = "" +
	"\n" +
	"\x1finternal/protocol/cluster.proto\x12\acluster\x1a\x1einternal/protocol/common.proto\"{\n" +
	"\x13RegisterNodeRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\"\xac\x01\n" +
	"\x14RegisterNodeResponse\x12/\n" +
	"\x06status\x18\x01 \x01(\x0e2\x17.cluster.RegisterStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12I\n" +
	"\x11assigned_protocol\x18\x03 \x01(\v2\x1c.protocol.ProtocolAssignmentR\x10assignedProtocol\"A\n" +
	"\x10HeartbeatRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x02 \x01(\tR\tclusterId\"#\n" +
	"\x11HeartbeatResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"-\n" +
	"\fPeersRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\"8\n" +
	"\rPeersResponse\x12'\n" +
	"\x05peers\x18\x01 \x03(\v2\x11.cluster.NodeInfoR\x05peers\"H\n" +
	"\bNodeInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\"\x92\x01\n" +
	"\n" +
	"LogRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05level\x18\x04 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"\x1d\n" +
	"\vLogResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"c\n" +
	"\x16NodeActionCapabilities\x12\x15\n" +
	"\x06kv_put\x18\x01 \x01(\bR\x05kvPut\x12\x15\n" +
	"\x06kv_get\x18\x02 \x01(\bR\x05kvGet\x12\x1b\n" +
	"\tkv_delete\x18\x03 \x01(\bR\bkvDelete\"\xfa\x01\n" +
	"\x1dReportNodeCapabilitiesRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12E\n" +
	"\x0factive_protocol\x18\x03 \x01(\v2\x1c.protocol.ProtocolAssignmentR\x0eactiveProtocol\x129\n" +
	"\aactions\x18\x04 \x01(\v2\x1f.cluster.NodeActionCapabilitiesR\aactions\x12\x1f\n" +
	"\vreported_at\x18\x05 \x01(\x03R\n" +
	"reportedAt\"J\n" +
	"\x1eReportNodeCapabilitiesResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*6\n" +
	"\x0eRegisterStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSUCCESS\x10\x01\x12\n" +
	"\n" +
	"\x06FAILED\x10\x022\x84\x03\n" +
	"\x13OrchestratorService\x12K\n" +
	"\fRegisterNode\x12\x1c.cluster.RegisterNodeRequest\x1a\x1d.cluster.RegisterNodeResponse\x12B\n" +
	"\tHeartbeat\x12\x19.cluster.HeartbeatRequest\x1a\x1a.cluster.HeartbeatResponse\x129\n" +
	"\bGetPeers\x12\x15.cluster.PeersRequest\x1a\x16.cluster.PeersResponse\x126\n" +
	"\tReportLog\x12\x13.cluster.LogRequest\x1a\x14.cluster.LogResponse\x12i\n" +
	"\x16ReportNodeCapabilities\x12&.cluster.ReportNodeCapabilitiesRequest\x1a'.cluster.ReportNodeCapabilitiesResponseB\x1cZ\x1afaultlab/internal/protocolb\x06proto3"

var (
	file_internal_protocol_cluster_proto_rawDescOnce sync.Once
	file_internal_protocol_cluster_proto_rawDescData []byte
)

func file_internal_protocol_cluster_proto_rawDescGZIP() []byte {
	file_internal_protocol_cluster_proto_rawDescOnce.Do(func() {
		file_internal_protocol_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_protocol_cluster_proto_rawDesc), len(file_internal_protocol_cluster_proto_rawDesc)))
	})
	return file_internal_protocol_cluster_proto_rawDescData
}

var file_internal_protocol_cluster_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_protocol_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_internal_protocol_cluster_proto_goTypes = []any{
	(RegisterStatus)(0),                    // 0: cluster.RegisterStatus
	(*RegisterNodeRequest)(nil),            // 1: cluster.RegisterNodeRequest
	(*RegisterNodeResponse)(nil),           // 2: cluster.RegisterNodeResponse
	(*HeartbeatRequest)(nil),               // 3: cluster.HeartbeatRequest
	(*HeartbeatResponse)(nil),              // 4: cluster.HeartbeatResponse
	(*PeersRequest)(nil),                   // 5: cluster.PeersRequest
	(*PeersResponse)(nil),                  // 6: cluster.PeersResponse
	(*NodeInfo)(nil),                       // 7: cluster.NodeInfo
	(*LogRequest)(nil),                     // 8: cluster.LogRequest
	(*LogResponse)(nil),                    // 9: cluster.LogResponse
	(*NodeActionCapabilities)(nil),         // 10: cluster.NodeActionCapabilities
	(*ReportNodeCapabilitiesRequest)(nil),  // 11: cluster.ReportNodeCapabilitiesRequest
	(*ReportNodeCapabilitiesResponse)(nil), // 12: cluster.ReportNodeCapabilitiesResponse
	(*ProtocolAssignment)(nil),             // 13: protocol.ProtocolAssignment
}
var file_internal_protocol_cluster_proto_depIdxs = []int32{
	0,  // 0: cluster.RegisterNodeResponse.status:type_name -> cluster.RegisterStatus
	13, // 1: cluster.RegisterNodeResponse.assigned_protocol:type_name -> protocol.ProtocolAssignment
	7,  // 2: cluster.PeersResponse.peers:type_name -> cluster.NodeInfo
	13, // 3: cluster.ReportNodeCapabilitiesRequest.active_protocol:type_name -> protocol.ProtocolAssignment
	10, // 4: cluster.ReportNodeCapabilitiesRequest.actions:type_name -> cluster.NodeActionCapabilities
	1,  // 5: cluster.OrchestratorService.RegisterNode:input_type -> cluster.RegisterNodeRequest
	3,  // 6: cluster.OrchestratorService.Heartbeat:input_type -> cluster.HeartbeatRequest
	5,  // 7: cluster.OrchestratorService.GetPeers:input_type -> cluster.PeersRequest
	8,  // 8: cluster.OrchestratorService.ReportLog:input_type -> cluster.LogRequest
	11, // 9: cluster.OrchestratorService.ReportNodeCapabilities:input_type -> cluster.ReportNodeCapabilitiesRequest
	2,  // 10: cluster.OrchestratorService.RegisterNode:output_type -> cluster.RegisterNodeResponse
	4,  // 11: cluster.OrchestratorService.Heartbeat:output_type -> cluster.HeartbeatResponse
	6,  // 12: cluster.OrchestratorService.GetPeers:output_type -> cluster.PeersResponse
	9,  // 13: cluster.OrchestratorService.ReportLog:output_type -> cluster.LogResponse
	12, // 14: cluster.OrchestratorService.ReportNodeCapabilities:output_type -> cluster.ReportNodeCapabilitiesResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_internal_protocol_cluster_proto_init() }
func file_internal_protocol_cluster_proto_init() {
	if File_internal_protocol_cluster_proto != nil {
		return
	}
	file_internal_protocol_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_protocol_cluster_proto_rawDesc), len(file_internal_protocol_cluster_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_protocol_cluster_proto_goTypes,
		DependencyIndexes: file_internal_protocol_cluster_proto_depIdxs,
		EnumInfos:         file_internal_protocol_cluster_proto_enumTypes,
		MessageInfos:      file_internal_protocol_cluster_proto_msgTypes,
	}.Build()
	File_internal_protocol_cluster_proto = out.File
	file_internal_protocol_cluster_proto_goTypes = nil
	file_internal_protocol_cluster_proto_depIdxs = nil
}
