// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/protocol/common.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ProtocolAssignment is the shared wire contract for protocol selection and
// protocol changes across controlplane and node runtime.
type ProtocolAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`      // e.g. gossip, raft
	Epoch         uint64                 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"` // monotonic cluster protocol version
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolAssignment) Reset() {
	*x = ProtocolAssignment{}
	mi := &file_internal_protocol_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolAssignment) ProtoMessage() {}

func (x *ProtocolAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolAssignment.ProtoReflect.Descriptor instead.
func (*ProtocolAssignment) Descriptor() ([]byte, []int) {
	return file_internal_protocol_common_proto_rawDescGZIP(), []int{0}
}

func (x *ProtocolAssignment) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ProtocolAssignment) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

var File_internal_protocol_common_proto protoreflect.FileDescriptor

const file_internal_protocol_common_proto_rawDesc = "" +
	"\n" +
	"\x1einternal/protocol/common.proto\x12\bprotocol\"<\n" +
	"\x12ProtocolAssignment\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x04R\x05epochB\x1cZ\x1afaultlab/internal/protocolb\x06proto3"

var (
	file_internal_protocol_common_proto_rawDescOnce sync.Once
	file_internal_protocol_common_proto_rawDescData []byte
)

func file_internal_protocol_common_proto_rawDescGZIP() []byte {
	file_internal_protocol_common_proto_rawDescOnce.Do(func() {
		file_internal_protocol_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_protocol_common_proto_rawDesc), len(file_internal_protocol_common_proto_rawDesc)))
	})
	return file_internal_protocol_common_proto_rawDescData
}

var file_internal_protocol_common_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_protocol_common_proto_goTypes = []any{
	(*ProtocolAssignment)(nil), // 0: protocol.ProtocolAssignment
}
var file_internal_protocol_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_protocol_common_proto_init() }
func file_internal_protocol_common_proto_init() {
	if File_internal_protocol_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_protocol_common_proto_rawDesc), len(file_internal_protocol_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_protocol_common_proto_goTypes,
		DependencyIndexes: file_internal_protocol_common_proto_depIdxs,
		MessageInfos:      file_internal_protocol_common_proto_msgTypes,
	}.Build()
	File_internal_protocol_common_proto = out.File
	file_internal_protocol_common_proto_goTypes = nil
	file_internal_protocol_common_proto_depIdxs = nil
}
