// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/protocol/node.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EnvelopeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"` // which protocol emitted this (raft / gossip / baseline etc)
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`   // Protocol specific serialized payload
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvelopeRequest) Reset() {
	*x = EnvelopeRequest{}
	mi := &file_internal_protocol_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvelopeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvelopeRequest) ProtoMessage() {}

func (x *EnvelopeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvelopeRequest.ProtoReflect.Descriptor instead.
func (*EnvelopeRequest) Descriptor() ([]byte, []int) {
	return file_internal_protocol_node_proto_rawDescGZIP(), []int{0}
}

func (x *EnvelopeRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *EnvelopeRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *EnvelopeRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *EnvelopeRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type EnvelopeAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvelopeAck) Reset() {
	*x = EnvelopeAck{}
	mi := &file_internal_protocol_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvelopeAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvelopeAck) ProtoMessage() {}

func (x *EnvelopeAck) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvelopeAck.ProtoReflect.Descriptor instead.
func (*EnvelopeAck) Descriptor() ([]byte, []int) {
	return file_internal_protocol_node_proto_rawDescGZIP(), []int{1}
}

func (x *EnvelopeAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EnvelopeAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HandshakeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Addr          string                 `protobuf:"bytes,3,opt,name=addr,proto3" json:"addr,omitempty"`
	Port          int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_internal_protocol_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_internal_protocol_node_proto_rawDescGZIP(), []int{2}
}

func (x *HandshakeRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *HandshakeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HandshakeRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *HandshakeRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type HandshakeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_internal_protocol_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_internal_protocol_node_proto_rawDescGZIP(), []int{3}
}

func (x *HandshakeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HandshakeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_internal_protocol_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_internal_protocol_node_proto_rawDescGZIP(), []int{4}
}

func (x *PingRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_internal_protocol_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_internal_protocol_node_proto_rawDescGZIP(), []int{5}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RemoveNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveNodeRequest) Reset() {
	*x = RemoveNodeRequest{}
	mi := &file_internal_protocol_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveNodeRequest) ProtoMessage() {}

func (x *RemoveNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveNodeRequest.ProtoReflect.Descriptor instead.
func (*RemoveNodeRequest) Descriptor() ([]byte, []int) {
	return file_internal_protocol_node_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveNodeRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *RemoveNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type RemoveNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveNodeResponse) Reset() {
	*x = RemoveNodeResponse{}
	mi := &file_internal_protocol_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveNodeResponse) ProtoMessage() {}

func (x *RemoveNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveNodeResponse.ProtoReflect.Descriptor instead.
func (*RemoveNodeResponse) Descriptor() ([]byte, []int) {
	return file_internal_protocol_node_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveNodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_protocol_node_proto protoreflect.FileDescriptor

const file_internal_protocol_node_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/protocol/node.proto\x12\bprotocol\"k\n" +
	"\x0fEnvelopeRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"A\n" +
	"\vEnvelopeAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"r\n" +
	"\x10HandshakeRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04addr\x18\x03 \x01(\tR\x04addr\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\"G\n" +
	"\x11HandshakeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"!\n" +
	"\vPingRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\"(\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"K\n" +
	"\x11RemoveNodeRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\".\n" +
	"\x12RemoveNodeResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\x93\x02\n" +
	"\vNodeService\x125\n" +
	"\x04Ping\x12\x15.protocol.PingRequest\x1a\x16.protocol.PingResponse\x12E\n" +
	"\bStopNode\x12\x1b.protocol.RemoveNodeRequest\x1a\x1c.protocol.RemoveNodeResponse\x12D\n" +
	"\tHandshake\x12\x1a.protocol.HandshakeRequest\x1a\x1b.protocol.HandshakeResponse\x12@\n" +
	"\fSendEnvelope\x12\x19.protocol.EnvelopeRequest\x1a\x15.protocol.EnvelopeAckB\x1cZ\x1afaultlab/internal/protocolb\x06proto3"

var (
	file_internal_protocol_node_proto_rawDescOnce sync.Once
	file_internal_protocol_node_proto_rawDescData []byte
)

func file_internal_protocol_node_proto_rawDescGZIP() []byte {
	file_internal_protocol_node_proto_rawDescOnce.Do(func() {
		file_internal_protocol_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_protocol_node_proto_rawDesc), len(file_internal_protocol_node_proto_rawDesc)))
	})
	return file_internal_protocol_node_proto_rawDescData
}

var file_internal_protocol_node_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_internal_protocol_node_proto_goTypes = []any{
	(*EnvelopeRequest)(nil),    // 0: protocol.EnvelopeRequest
	(*EnvelopeAck)(nil),        // 1: protocol.EnvelopeAck
	(*HandshakeRequest)(nil),   // 2: protocol.HandshakeRequest
	(*HandshakeResponse)(nil),  // 3: protocol.HandshakeResponse
	(*PingRequest)(nil),        // 4: protocol.PingRequest
	(*PingResponse)(nil),       // 5: protocol.PingResponse
	(*RemoveNodeRequest)(nil),  // 6: protocol.RemoveNodeRequest
	(*RemoveNodeResponse)(nil), // 7: protocol.RemoveNodeResponse
}
var file_internal_protocol_node_proto_depIdxs = []int32{
	4, // 0: protocol.NodeService.Ping:input_type -> protocol.PingRequest
	6, // 1: protocol.NodeService.StopNode:input_type -> protocol.RemoveNodeRequest
	2, // 2: protocol.NodeService.Handshake:input_type -> protocol.HandshakeRequest
	0, // 3: protocol.NodeService.SendEnvelope:input_type -> protocol.EnvelopeRequest
	5, // 4: protocol.NodeService.Ping:output_type -> protocol.PingResponse
	7, // 5: protocol.NodeService.StopNode:output_type -> protocol.RemoveNodeResponse
	3, // 6: protocol.NodeService.Handshake:output_type -> protocol.HandshakeResponse
	1, // 7: protocol.NodeService.SendEnvelope:output_type -> protocol.EnvelopeAck
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_protocol_node_proto_init() }
func file_internal_protocol_node_proto_init() {
	if File_internal_protocol_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_protocol_node_proto_rawDesc), len(file_internal_protocol_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_protocol_node_proto_goTypes,
		DependencyIndexes: file_internal_protocol_node_proto_depIdxs,
		MessageInfos:      file_internal_protocol_node_proto_msgTypes,
	}.Build()
	File_internal_protocol_node_proto = out.File
	file_internal_protocol_node_proto_goTypes = nil
	file_internal_protocol_node_proto_depIdxs = nil
}
