// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: internal/protocol/node.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ActionType int32

const (
	ActionType_ACTION_UNKNOWN ActionType = 0
	ActionType_KV_PUT         ActionType = 1
	ActionType_KV_GET         ActionType = 2
	ActionType_KV_DELETE      ActionType = 3
)

// Enum value maps for ActionType.
var (
	ActionType_name = map[int32]string{
		0: "ACTION_UNKNOWN",
		1: "KV_PUT",
		2: "KV_GET",
		3: "KV_DELETE",
	}
	ActionType_value = map[string]int32{
		"ACTION_UNKNOWN": 0,
		"KV_PUT":         1,
		"KV_GET":         2,
		"KV_DELETE":      3,
	}
)

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}

func (x ActionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ActionType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_protocol_node_proto_enumTypes[0].Descriptor()
}

func (ActionType) Type() protoreflect.EnumType {
	return &file_internal_protocol_node_proto_enumTypes[0]
}

func (x ActionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ActionType.Descriptor instead.
func (ActionType) EnumDescriptor() ([]byte, []int) {
	return file_internal_protocol_node_proto_rawDescGZIP(), []int{0}
}

type ChangeProtocolRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ClusterId        string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	NodeId           string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	AssignedProtocol *ProtocolAssignment    `protobuf:"bytes,3,opt,name=assigned_protocol,json=assignedProtocol,proto3" json:"assigned_protocol,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ChangeProtocolRequest) Reset() {
	*x = ChangeProtocolRequest{}
	mi := &file_internal_protocol_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeProtocolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeProtocolRequest) ProtoMessage() {}

func (x *ChangeProtocolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeProtocolRequest.ProtoReflect.Descriptor instead.
func (*ChangeProtocolRequest) Descriptor() ([]byte, []int) {
	return file_internal_protocol_node_proto_rawDescGZIP(), []int{0}
}

func (x *ChangeProtocolRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *ChangeProtocolRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ChangeProtocolRequest) GetAssignedProtocol() *ProtocolAssignment {
	if x != nil {
		return x.AssignedProtocol
	}
	return nil
}

type ChangeProtocolResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Done           bool                   `protobuf:"varint,1,opt,name=done,proto3" json:"done,omitempty"`
	ActiveProtocol *ProtocolAssignment    `protobuf:"bytes,2,opt,name=active_protocol,json=activeProtocol,proto3" json:"active_protocol,omitempty"`
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChangeProtocolResponse) Reset() {
	*x = ChangeProtocolResponse{}
	mi := &file_internal_protocol_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeProtocolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeProtocolResponse) ProtoMessage() {}

func (x *ChangeProtocolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeProtocolResponse.ProtoReflect.Descriptor instead.
func (*ChangeProtocolResponse) Descriptor() ([]byte, []int) {
	return file_internal_protocol_node_proto_rawDescGZIP(), []int{1}
}

func (x *ChangeProtocolResponse) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *ChangeProtocolResponse) GetActiveProtocol() *ProtocolAssignment {
	if x != nil {
		return x.ActiveProtocol
	}
	return nil
}

func (x *ChangeProtocolResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ActionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Action        ActionType             `protobuf:"varint,2,opt,name=action,proto3,enum=protocol.ActionType" json:"action,omitempty"` // "kv.put", "kv.get"
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionRequest) Reset() {
	*x = ActionRequest{}
	mi := &file_internal_protocol_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionRequest) ProtoMessage() {}

func (x *ActionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionRequest.ProtoReflect.Descriptor instead.
func (*ActionRequest) Descriptor() ([]byte, []int) {
	return file_internal_protocol_node_proto_rawDescGZIP(), []int{2}
}

func (x *ActionRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ActionRequest) GetAction() ActionType {
	if x != nil {
		return x.Action
	}
	return ActionType_ACTION_UNKNOWN
}

func (x *ActionRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ActionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Payload       []byte                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"` // used for returning data (like get)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionResponse) Reset() {
	*x = ActionResponse{}
	mi := &file_internal_protocol_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionResponse) ProtoMessage() {}

func (x *ActionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionResponse.ProtoReflect.Descriptor instead.
func (*ActionResponse) Descriptor() ([]byte, []int) {
	return file_internal_protocol_node_proto_rawDescGZIP(), []int{3}
}

func (x *ActionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ActionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ActionResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// structure of payload for kv.put and kv.get
type KVPutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVPutRequest) Reset() {
	*x = KVPutRequest{}
	mi := &file_internal_protocol_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVPutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVPutRequest) ProtoMessage() {}

func (x *KVPutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVPutRequest.ProtoReflect.Descriptor instead.
func (*KVPutRequest) Descriptor() ([]byte, []int) {
	return file_internal_protocol_node_proto_rawDescGZIP(), []int{4}
}

func (x *KVPutRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KVPutRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type KVGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVGetRequest) Reset() {
	*x = KVGetRequest{}
	mi := &file_internal_protocol_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVGetRequest) ProtoMessage() {}

func (x *KVGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVGetRequest.ProtoReflect.Descriptor instead.
func (*KVGetRequest) Descriptor() ([]byte, []int) {
	return file_internal_protocol_node_proto_rawDescGZIP(), []int{5}
}

func (x *KVGetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type KVGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Version       int64                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	Origin        string                 `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
	HasMetadata   bool                   `protobuf:"varint,4,opt,name=has_metadata,json=hasMetadata,proto3" json:"has_metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVGetResponse) Reset() {
	*x = KVGetResponse{}
	mi := &file_internal_protocol_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVGetResponse) ProtoMessage() {}

func (x *KVGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVGetResponse.ProtoReflect.Descriptor instead.
func (*KVGetResponse) Descriptor() ([]byte, []int) {
	return file_internal_protocol_node_proto_rawDescGZIP(), []int{6}
}

func (x *KVGetResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *KVGetResponse) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *KVGetResponse) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

func (x *KVGetResponse) GetHasMetadata() bool {
	if x != nil {
		return x.HasMetadata
	}
	return false
}

type KVDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVDeleteRequest) Reset() {
	*x = KVDeleteRequest{}
	mi := &file_internal_protocol_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVDeleteRequest) ProtoMessage() {}

func (x *KVDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVDeleteRequest.ProtoReflect.Descriptor instead.
func (*KVDeleteRequest) Descriptor() ([]byte, []int) {
	return file_internal_protocol_node_proto_rawDescGZIP(), []int{7}
}

func (x *KVDeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type EnvelopeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"` // which protocol emitted this (raft / gossip / baseline etc)
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`   // Protocol specific serialized payload
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvelopeRequest) Reset() {
	*x = EnvelopeRequest{}
	mi := &file_internal_protocol_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvelopeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvelopeRequest) ProtoMessage() {}

func (x *EnvelopeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvelopeRequest.ProtoReflect.Descriptor instead.
func (*EnvelopeRequest) Descriptor() ([]byte, []int) {
	return file_internal_protocol_node_proto_rawDescGZIP(), []int{8}
}

func (x *EnvelopeRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *EnvelopeRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *EnvelopeRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *EnvelopeRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type EnvelopeAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvelopeAck) Reset() {
	*x = EnvelopeAck{}
	mi := &file_internal_protocol_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvelopeAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvelopeAck) ProtoMessage() {}

func (x *EnvelopeAck) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvelopeAck.ProtoReflect.Descriptor instead.
func (*EnvelopeAck) Descriptor() ([]byte, []int) {
	return file_internal_protocol_node_proto_rawDescGZIP(), []int{9}
}

func (x *EnvelopeAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EnvelopeAck) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type HandshakeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Addr          string                 `protobuf:"bytes,3,opt,name=addr,proto3" json:"addr,omitempty"`
	Port          int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_internal_protocol_node_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_node_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_internal_protocol_node_proto_rawDescGZIP(), []int{10}
}

func (x *HandshakeRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *HandshakeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HandshakeRequest) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *HandshakeRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type HandshakeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_internal_protocol_node_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_node_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_internal_protocol_node_proto_rawDescGZIP(), []int{11}
}

func (x *HandshakeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *HandshakeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	From          string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_internal_protocol_node_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_node_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_internal_protocol_node_proto_rawDescGZIP(), []int{12}
}

func (x *PingRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_internal_protocol_node_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_node_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_internal_protocol_node_proto_rawDescGZIP(), []int{13}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RemoveNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterId     string                 `protobuf:"bytes,1,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveNodeRequest) Reset() {
	*x = RemoveNodeRequest{}
	mi := &file_internal_protocol_node_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveNodeRequest) ProtoMessage() {}

func (x *RemoveNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_node_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveNodeRequest.ProtoReflect.Descriptor instead.
func (*RemoveNodeRequest) Descriptor() ([]byte, []int) {
	return file_internal_protocol_node_proto_rawDescGZIP(), []int{14}
}

func (x *RemoveNodeRequest) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *RemoveNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type RemoveNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveNodeResponse) Reset() {
	*x = RemoveNodeResponse{}
	mi := &file_internal_protocol_node_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveNodeResponse) ProtoMessage() {}

func (x *RemoveNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_node_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveNodeResponse.ProtoReflect.Descriptor instead.
func (*RemoveNodeResponse) Descriptor() ([]byte, []int) {
	return file_internal_protocol_node_proto_rawDescGZIP(), []int{15}
}

func (x *RemoveNodeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FaultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Crashed       bool                   `protobuf:"varint,2,opt,name=crashed,proto3" json:"crashed,omitempty"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	DropRate      float64                `protobuf:"fixed64,3,opt,name=drop_rate,json=dropRate,proto3" json:"drop_rate,omitempty"`
	DelayMs       int32                  `protobuf:"varint,4,opt,name=delay_ms,json=delayMs,proto3" json:"delay_ms,omitempty"`
	Partition     []string               `protobuf:"bytes,5,rep,name=partition,proto3" json:"partition,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FaultRequest) Reset() {
	*x = FaultRequest{}
	mi := &file_internal_protocol_node_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FaultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaultRequest) ProtoMessage() {}

func (x *FaultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_node_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaultRequest.ProtoReflect.Descriptor instead.
func (*FaultRequest) Descriptor() ([]byte, []int) {
	return file_internal_protocol_node_proto_rawDescGZIP(), []int{16}
}

func (x *FaultRequest) GetCrashed() bool {
	if x != nil {
		return x.Crashed
	}
	return false
}

func (x *FaultRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *FaultRequest) GetDropRate() float64 {
	if x != nil {
		return x.DropRate
	}
	return 0
}

func (x *FaultRequest) GetDelayMs() int32 {
	if x != nil {
		return x.DelayMs
	}
	return 0
}

func (x *FaultRequest) GetPartition() []string {
	if x != nil {
		return x.Partition
	}
	return nil
}

type FaultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FaultResponse) Reset() {
	*x = FaultResponse{}
	mi := &file_internal_protocol_node_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FaultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaultResponse) ProtoMessage() {}

func (x *FaultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_node_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaultResponse.ProtoReflect.Descriptor instead.
func (*FaultResponse) Descriptor() ([]byte, []int) {
	return file_internal_protocol_node_proto_rawDescGZIP(), []int{17}
}

func (x *FaultResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FaultResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_internal_protocol_node_proto protoreflect.FileDescriptor

const file_internal_protocol_node_proto_rawDesc = "" +
	"\n" +
	"\x1cinternal/protocol/node.proto\x12\bprotocol\x1a\x1einternal/protocol/common.proto\"\x9a\x01\n" +
	"\x15ChangeProtocolRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12I\n" +
	"\x11assigned_protocol\x18\x03 \x01(\v2\x1c.protocol.ProtocolAssignmentR\x10assignedProtocol\"\x8d\x01\n" +
	"\x16ChangeProtocolResponse\x12\x12\n" +
	"\x04done\x18\x01 \x01(\bR\x04done\x12E\n" +
	"\x0factive_protocol\x18\x02 \x01(\v2\x1c.protocol.ProtocolAssignmentR\x0eactiveProtocol\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"p\n" +
	"\rActionRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12,\n" +
	"\x06action\x18\x02 \x01(\x0e2\x14.protocol.ActionTypeR\x06action\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"^\n" +
	"\x0eActionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\"6\n" +
	"\fKVPutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\" \n" +
	"\fKVGetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"z\n" +
	"\rKVGetResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x03R\aversion\x12\x16\n" +
	"\x06origin\x18\x03 \x01(\tR\x06origin\x12!\n" +
	"\fhas_metadata\x18\x04 \x01(\bR\vhasMetadata\"#\n" +
	"\x0fKVDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"k\n" +
	"\x0fEnvelopeRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"A\n" +
	"\vEnvelopeAck\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"r\n" +
	"\x10HandshakeRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04addr\x18\x03 \x01(\tR\x04addr\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\"G\n" +
	"\x11HandshakeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"!\n" +
	"\vPingRequest\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\"(\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"K\n" +
	"\x11RemoveNodeRequest\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x01 \x01(\tR\tclusterId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\".\n" +
	"\x12RemoveNodeResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x97\x01\n" +
	"\fFaultRequest\x12\x18\n" +
	"\acrashed\x18\x02 \x01(\bR\acrashed\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tdrop_rate\x18\x03 \x01(\x01R\bdropRate\x12\x19\n" +
	"\bdelay_ms\x18\x04 \x01(\x05R\adelayMs\x12\x1c\n" +
	"\tpartition\x18\x05 \x03(\tR\tpartition\"C\n" +
	"\rFaultResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*G\n" +
	"\n" +
	"ActionType\x12\x12\n" +
	"\x0eACTION_UNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06KV_PUT\x10\x01\x12\n" +
	"\n" +
	"\x06KV_GET\x10\x02\x12\r\n" +
	"\tKV_DELETE\x10\x032\xef\x03\n" +
	"\vNodeService\x125\n" +
	"\x04Ping\x12\x15.protocol.PingRequest\x1a\x16.protocol.PingResponse\x12E\n" +
	"\bStopNode\x12\x1b.protocol.RemoveNodeRequest\x1a\x1c.protocol.RemoveNodeResponse\x12D\n" +
	"\tHandshake\x12\x1a.protocol.HandshakeRequest\x1a\x1b.protocol.HandshakeResponse\x12@\n" +
	"\fSendEnvelope\x12\x19.protocol.EnvelopeRequest\x1a\x15.protocol.EnvelopeAck\x12A\n" +
	"\x0eSetFaultParams\x12\x16.protocol.FaultRequest\x1a\x17.protocol.FaultResponse\x12B\n" +
	"\rExecuteAction\x12\x17.protocol.ActionRequest\x1a\x18.protocol.ActionResponse\x12S\n" +
	"\x0eChangeProtocol\x12\x1f.protocol.ChangeProtocolRequest\x1a .protocol.ChangeProtocolResponseB\x1cZ\x1afaultlab/internal/protocolb\x06proto3"

var (
	file_internal_protocol_node_proto_rawDescOnce sync.Once
	file_internal_protocol_node_proto_rawDescData []byte
)

func file_internal_protocol_node_proto_rawDescGZIP() []byte {
	file_internal_protocol_node_proto_rawDescOnce.Do(func() {
		file_internal_protocol_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_protocol_node_proto_rawDesc), len(file_internal_protocol_node_proto_rawDesc)))
	})
	return file_internal_protocol_node_proto_rawDescData
}

var file_internal_protocol_node_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_protocol_node_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_internal_protocol_node_proto_goTypes = []any{
	(ActionType)(0),                // 0: protocol.ActionType
	(*ChangeProtocolRequest)(nil),  // 1: protocol.ChangeProtocolRequest
	(*ChangeProtocolResponse)(nil), // 2: protocol.ChangeProtocolResponse
	(*ActionRequest)(nil),          // 3: protocol.ActionRequest
	(*ActionResponse)(nil),         // 4: protocol.ActionResponse
	(*KVPutRequest)(nil),           // 5: protocol.KVPutRequest
	(*KVGetRequest)(nil),           // 6: protocol.KVGetRequest
	(*KVGetResponse)(nil),          // 7: protocol.KVGetResponse
	(*KVDeleteRequest)(nil),        // 8: protocol.KVDeleteRequest
	(*EnvelopeRequest)(nil),        // 9: protocol.EnvelopeRequest
	(*EnvelopeAck)(nil),            // 10: protocol.EnvelopeAck
	(*HandshakeRequest)(nil),       // 11: protocol.HandshakeRequest
	(*HandshakeResponse)(nil),      // 12: protocol.HandshakeResponse
	(*PingRequest)(nil),            // 13: protocol.PingRequest
	(*PingResponse)(nil),           // 14: protocol.PingResponse
	(*RemoveNodeRequest)(nil),      // 15: protocol.RemoveNodeRequest
	(*RemoveNodeResponse)(nil),     // 16: protocol.RemoveNodeResponse
	(*FaultRequest)(nil),           // 17: protocol.FaultRequest
	(*FaultResponse)(nil),          // 18: protocol.FaultResponse
	(*ProtocolAssignment)(nil),     // 19: protocol.ProtocolAssignment
}
var file_internal_protocol_node_proto_depIdxs = []int32{
	19, // 0: protocol.ChangeProtocolRequest.assigned_protocol:type_name -> protocol.ProtocolAssignment
	19, // 1: protocol.ChangeProtocolResponse.active_protocol:type_name -> protocol.ProtocolAssignment
	0,  // 2: protocol.ActionRequest.action:type_name -> protocol.ActionType
	13, // 3: protocol.NodeService.Ping:input_type -> protocol.PingRequest
	15, // 4: protocol.NodeService.StopNode:input_type -> protocol.RemoveNodeRequest
	11, // 5: protocol.NodeService.Handshake:input_type -> protocol.HandshakeRequest
	9,  // 6: protocol.NodeService.SendEnvelope:input_type -> protocol.EnvelopeRequest
	17, // 7: protocol.NodeService.SetFaultParams:input_type -> protocol.FaultRequest
	3,  // 8: protocol.NodeService.ExecuteAction:input_type -> protocol.ActionRequest
	1,  // 9: protocol.NodeService.ChangeProtocol:input_type -> protocol.ChangeProtocolRequest
	14, // 10: protocol.NodeService.Ping:output_type -> protocol.PingResponse
	16, // 11: protocol.NodeService.StopNode:output_type -> protocol.RemoveNodeResponse
	12, // 12: protocol.NodeService.Handshake:output_type -> protocol.HandshakeResponse
	10, // 13: protocol.NodeService.SendEnvelope:output_type -> protocol.EnvelopeAck
	18, // 14: protocol.NodeService.SetFaultParams:output_type -> protocol.FaultResponse
	4,  // 15: protocol.NodeService.ExecuteAction:output_type -> protocol.ActionResponse
	2,  // 16: protocol.NodeService.ChangeProtocol:output_type -> protocol.ChangeProtocolResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_internal_protocol_node_proto_init() }
func file_internal_protocol_node_proto_init() {
	if File_internal_protocol_node_proto != nil {
		return
	}
	file_internal_protocol_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_protocol_node_proto_rawDesc), len(file_internal_protocol_node_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_protocol_node_proto_goTypes,
		DependencyIndexes: file_internal_protocol_node_proto_depIdxs,
		EnumInfos:         file_internal_protocol_node_proto_enumTypes,
		MessageInfos:      file_internal_protocol_node_proto_msgTypes,
	}.Build()
	File_internal_protocol_node_proto = out.File
	file_internal_protocol_node_proto_goTypes = nil
	file_internal_protocol_node_proto_depIdxs = nil
}
